### PR TITLE
Introducing IRequestCorrelationProvider abstraction (addresses #11)

### PR DESCRIPTION
**Pull request by drub0y**
* Added IRequestCorrelationProvider interface
 * Added fluent configuration support for configuring IRequestCorrelationProvider
 * Implemented DefaultRequestCorrelationProvider that takes the previously implemented rules from RequestExtensions::SetCorrelationIds *except* that I now only set RequesterId if it's null/empty (that way application logic has opportunity to override provider logic at all times)

### CODE REVIEW

**Comment by drub0y** [comment]
So I took care of all the renaming stuff, no problems there.

I'm not following your comment about the `RequesterId/RequestId` being overridden in `ServiceBusClient` though. The only place I saw it was where I replaced the call to the extension method with a call to the provider now which is [right here](https://github.com/inter8ection/Obvs/pull/12/files#diff-7c975a620c5cf670543959e5919850baR77).

Ohhh, I think maybe you meant `ServiceEndpointClient`? I hadn't noticed it was being set there as well in `GetResponses`. Ok let me figure that out, will need to get the `IRequestCorrelationProvider` injected into there as well I guess. Will update the PR when that's ready.

**Comment by drub0y** [comment]
Ok, that was relatively easy. I believe your comments have fully been addressed now. Let me know if there's anything else, otherwise it's up to you when/if you want to pull this in.

**Comment by inter8ection** [comment]
Yeah sorry I mean `ServiceEndpointClient`. I can't remember a reason for it being overridden in there...

**Comment by inter8ection** [comment]
Merged and published to NuGet as 1.6.0, just updating the serialization packages now

**Pull request merged**
